version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: bank-api
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bank
      DB_HOST: mysql
      DB_PORT: 3306

volumes:
  mysql_data:
